module Nash
  VERSION: String

  class Nash[unchecked out K, unchecked out V] < Object
    include Enumerable[[ K, V, K ]]

    public

    def original_key: (K) -> unchecked out K

    def clear: () -> self

    def keys: () -> Array[K]

    def length: () -> Integer
    alias size length

    def ==: (untyped other) -> bool

    def []: (K) -> V

    def each: () { ([ K, V, K ]) -> untyped } -> self
            | () -> ::Enumerator[[ K, V, K ], self]
    alias each_pair each

    def filter: () { (K, V, K) -> boolish } -> Nash[K, V]
              | () -> Enumerator[[ K, V, K ], Nash[K, V]]
    alias select filter

    def has_key?: (K) -> bool
    alias key? has_key?
    alias include? has_key?
    alias member? has_key?

    def inspect: () -> String

    def store: (K, V) -> V
    alias []= store

    def to_hash: () -> Hash[K, V]

    def values: () -> Array[V]

    private

    def initialize: () { (K) -> unchecked out K } -> void
  end
end
