module Nash
  VERSION: String

  class Nash[unchecked out K, unchecked out V] < Object
    def initialize: () { (K) -> unchecked out K } -> void

    def normalize: (K) -> unchecked out K

    def store: (K, V) -> V
    alias []= store

    def []: (K) -> V

    def to_hash: () -> Hash[K, V]

    def inspect: () -> String
  end
end
