module Tash
  VERSION: String

  class Tash[unchecked out K, unchecked out V] < Object
    include Enumerable[[ K, V ]]

    def self.[]: [U, V] (Tash[U, V]) -> Tash[U, V]
               | [U, V] (_ToHash[U, V]) { (U) -> unchecked out U } -> Tash[U, V]
               | [U, V] (Array[[ U, V ]])  { (U) -> unchecked out U } -> Tash[U, V]
               | (*untyped) { (U) -> unchecked out U } -> Tash[untyped, untyped]

    public

    def <: [A, B] (Hash[A, B]) -> bool

    def <=: [A, B] (Hash[A, B]) -> bool

    def ==: (untyped other) -> bool

    def >: [A, B] (Hash[A, B]) -> bool

    def >=: [A, B] (Hash[A, B]) -> bool

    def []: (K) -> V

    def []=: (K, V) -> V

    def assoc: (K) -> [ K, V ]?

    def clear: () -> self

    def compact: () -> Tash[K, V]

    def compact!: () -> self?

    def default: (?K) -> V?

    def default=: (V) -> V

    def default_proc: () -> (Proc | nil)

    def default_proc=: (Proc | _ToProc | nil) -> (Proc | _ToProc | nil)

    def delete: (K) -> V?
              | [U] (K) { (K) -> U } -> (U | V)

    def each: () { ([ K, V ]) -> untyped } -> self
            | () -> ::Enumerator[[ K, V ], self]

    alias each_pair each

    def empty?: () -> bool

    def fetch: (K) -> V
             | [X] (K, X) -> (V | X)
             | [X] (K) { (K) -> X } -> (V | X)

    alias select filter

    def has_key?: (K) -> bool

    alias include? has_key?

    def inspect: () -> String

    alias key? has_key?

    def keys: () -> Array[K]

    def length: () -> Integer

    alias member? has_key?

    def select: () { (K, V) -> boolish } -> Tash[K, V]
              | () -> Enumerator[[ K, V ], Tash[K, V]]

    alias size length

    alias store []=

    def to_hash: () -> Hash[K, V]

    def values: () -> Array[V]

    private

    def initialize: () { (K) -> unchecked out K } -> void
  end
end
